#-------------------------------------#
#--- Welcome to NAQADAQE Portfolio ---#
#-------------------------------------#

# About Website
title: Naqadaqe Studio | Polyglot Web Strategy
author: Quik Naqadaqe
description: >- # My Site Description 
  
  Naqadaqe is a polyglot web strategist to save businesses from tedious workload. 
  Most afordable price and highest quality for your businesses or startup with minimal effort.
  Book a web service with Naqadaqe Studio Now!

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://naqadaqe.github.io/" # the base hostname & protocol for your site

# Social Links
email: naqadaqe@gmail.com
twitter_username: ...
github_username:  naqadaqe

# Build settings
markdown: kramdown
theme: minima
timezone: Asia/Kuala_Lumpur
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
# google_analytics: "UA-XXXXXXXX-X"

# Default Front Matter
defaults:
  -
    scope:
      path: ""
      type: "posts"

    values:
      layout: "post"
      separator: "|"
      permalink: /:categories/:title.html

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

